### ISSUE TITLE
Request for new asa fields

### ISSUE THREAD

**Issue by mobilederek** [xanzy/terraform-provider-ciscoasa#8]
I'm working on a government project where we are using this provider to manage extended ACLs and would like to request the following fields be added to the provider:
- Remarks
- Position (Is this the same as line #? I've been having issues being able to get the rules to show up in the same order as they are written in terraform)
- RuleLogging
  
Also, is there a way to use the provider to attach the new created extended ACL to an interface or is that a step that has the done manually the first time? 

Thanks,
Derek Smith
202-430-3790

**Comment by svanharmelen** [comment]
Hi @mobilederek! Let me see what I can do to help you out. For now the biggest challenge I have, is that I no longer have access to an ASA appliance.

I created this provider together with a former colleague at my former employer. We created it with a very specific use case in mind, so I'm not surprised you are missing some features. Updating it now to make it a bit more generic seems like a good thing, but will require some time and access to an ASA in order to validate any changes.

The work on itself should not be too much or too difficult, so I'll ask around a bit to see if I can get access to an ASA...

**Comment by svanharmelen** [comment]
Hi @mobilederek! Yeah, I actually managed to get access to an appliance 👍 But I didn't have time to look into the changes you requested yet.

I'm a little busy with work an ongoing project, but I'll try to make some time for this later this week of next week...

**Comment by svanharmelen** [comment]
@mobilederek would you be able to take the code in PR #9 for a spin? I think the update should add the fields you requested.

Let me know if you have any issues or if something is still missing...

**Comment by svanharmelen** [comment]
The requested changes are already merged into master, so I'm going to close this issue for now.
